# Generated by Django 3.1.2 on 2021-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='quantityproduct',
            old_name='product',
            new_name='productId',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='API.QuantityProduct'),
        ),
    ]
